version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    image: schoolhub-server
    command: npm run start
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/schoolhub
      - JWT_SECRET=${JWT_SECRET:-supersecretchangeme}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:5173}
    ports:
      - '4000:4000'
    depends_on:
      - mongo

volumes:
  mongo_data:

